version: 2.0
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout # check out source code to working directory
      - run: mkdir test-results
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run python test_gilded_rose.py > test-results/file.txt
      - store_test_results: # Upload test results for display in Test Summary
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts
          path: test-results
          destination: tr1
